"use strict";
const fs=require("fs"),path=require("path");
const {stableOutputHash}=require("../tools/output-hash");
const ORIGIN="https://edgeone-page.edgeone.app";
const L={"zh-CN":{name:"EdgeOne Page 中文站",description:"面向腾讯云 EdgeOne Pages 的简体中文和英文双语站点。",offline:"当前处于离线状态",message:"网络恢复后，请刷新页面继续浏览。已经访问过的页面仍可离线打开。",home:"返回中文首页",reload:"重新加载"},en:{name:"EdgeOne Page English",description:"A Simplified Chinese and English Hexo site optimized for Tencent EdgeOne Pages.",offline:"You are offline",message:"Refresh after your connection returns. Pages you already visited may still be available offline.",home:"Back to English home",reload:"Reload"}};
const lang=()=>{const v=hexo.config.language,x=Array.isArray(v)?v[0]:v;return x==="en"?"en":"zh-CN"};
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;");
function meta(h,k,a="name"){const q=k.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),p=[new RegExp(`<meta[^>]+${a}=["']${q}["'][^>]+content=["']([^"']*)["']`,"i"),new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+${a}=["']${q}["']`,"i")];for(const r of p){const m=h.match(r);if(m)return m[1].trim()}return""}
const title=h=>{const m=h.match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?m[1].replace(/<[^>]+>/g,"").trim():"EdgeOne Page"};
const url=(l,r)=>new URL(`/${l}/${String(r||"").replace(/^\/+/,"").replace(/index\.html$/i,"")}`,ORIGIN).href;
function schema(h,l,r){const o=L[l],u=url(l,r),t=title(h).replace(/\s+\|\s+EdgeOne Page.*$/i,"")||"EdgeOne Page",d=meta(h,"description")||o.description,a=meta(h,"author")||hexo.config.author||"FukunHennan",org=`${ORIGIN}/#organization`,site=`${ORIGIN}/${l}/#website`,g=[{"@type":"Organization","@id":org,name:"EdgeOne Page",url:ORIGIN,logo:{"@type":"ImageObject",url:`${ORIGIN}/icons/edgeone-icon.svg`}},{"@type":"WebSite","@id":site,name:o.name,url:`${ORIGIN}/${l}/`,description:o.description,inLanguage:l,publisher:{"@id":org}}];if(String(r||"").startsWith("posts/")){const x={"@type":"BlogPosting","@id":`${u}#article`,headline:t,description:d,url:u,mainEntityOfPage:{"@id":u},inLanguage:l,author:{"@type":"Person",name:a},publisher:{"@id":org},isPartOf:{"@id":site}},p=meta(h,"article:published_time","property"),m=meta(h,"article:modified_time","property")||p;if(p)x.datePublished=p;if(m)x.dateModified=m;g.push(x)}return{"@context":"https://schema.org","@graph":g}}
function inject(h,d){if(!h.includes("</head>"))return h;const l=lang(),o=L[l],r=String(d?.path||"").replace(/^\/+/,""),a=[];if(!h.includes('rel="manifest"'))a.push(`<link rel="manifest" href="/${l}/manifest.webmanifest">`);if(!h.includes('type="application/rss+xml"'))a.push(`<link rel="alternate" type="application/rss+xml" title="${esc(o.name)} RSS" href="/${l}/feed.xml">`);if(!h.includes('name="application-name"'))a.push(`<meta name="application-name" content="${esc(o.name)}"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="mobile-web-app-capable" content="yes">`);if(!h.includes("data-edgeone-schema"))a.push(`<script type="application/ld+json" data-edgeone-schema>${JSON.stringify(schema(h,l,r)).replace(/</g,"\\u003c")}</script>`);if(!h.includes("data-edgeone-service-worker"))a.push('<script data-edgeone-service-worker>(()=>{if(!("serviceWorker" in navigator)||!(location.protocol==="https:"||location.hostname==="localhost"))return;window.addEventListener("load",()=>navigator.serviceWorker.register("/service-worker.js",{scope:"/",updateViaCache:"none"}).then(r=>r.update().catch(()=>{})).catch(e=>console.error("[edgeone-page] Service worker registration failed:",e)),{once:true})})()</script>');return a.length?h.replace("</head>",`${a.join("\n")}\n</head>`):h}
function worker(v){return`"use strict";\nconst P="edgeone-page-",C=P+"${v}",CORE=["/zh-CN/","/en/","/zh-CN/offline.html","/en/offline.html","/icons/edgeone-icon.svg"],A=new Set(["style","script","image","font"]),ok=r=>r&&r.ok&&r.status===200&&r.type!=="opaque";async function put(q,r){if(!ok(r))return r;try{(await caches.open(C)).put(q,r.clone())}catch(e){}return r}self.addEventListener("install",e=>e.waitUntil(caches.open(C).then(c=>Promise.allSettled(CORE.map(u=>c.add(new Request(u,{cache:"reload"}))))).then(()=>self.skipWaiting())));self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x.startsWith(P)&&x!==C).map(x=>caches.delete(x)))).then(()=>self.clients.claim())));self.addEventListener("fetch",e=>{const q=e.request;if(q.method!=="GET"||q.headers.has("range"))return;const u=new URL(q.url);if(u.origin!==self.location.origin||u.pathname==="/service-worker.js")return;if(q.mode==="navigate"){e.respondWith(fetch(q).then(r=>put(q,r)).catch(async()=>await caches.match(q,{ignoreSearch:true})||await caches.match(u.pathname.startsWith("/en/")?"/en/offline.html":"/zh-CN/offline.html")||Response.error()));return}if(A.has(q.destination))e.respondWith(caches.match(q).then(c=>{const n=fetch(q).then(r=>put(q,r));if(c){e.waitUntil(n.catch(()=>{}));return c}return n.catch(()=>Response.error())}))});\n`}
function finalize(root=path.resolve(hexo.base_dir,"public")){const v=stableOutputHash(root,{exclude:["service-worker.js",".DS_Store"]});fs.writeFileSync(path.join(root,"service-worker.js"),worker(v),"utf8");return v}
function generate(){const l=lang(),o=L[l],root=path.resolve(hexo.base_dir,"public"),dir=path.join(root,l),icons=path.join(root,"icons");fs.mkdirSync(dir,{recursive:true});fs.mkdirSync(icons,{recursive:true});const icon='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#2563eb"/><stop offset="1" stop-color="#14b8a6"/></linearGradient></defs><rect width="512" height="512" rx="112" fill="url(#g)"/><path d="M132 142h248v62H202v51h158v60H202v55h184v62H132V142z" fill="#fff"/></svg>';fs.writeFileSync(path.join(icons,"edgeone-icon.svg"),icon,"utf8");const m={id:`/${l}/`,name:o.name,short_name:"EdgeOne Page",description:o.description,lang:l,start_url:`/${l}/`,scope:`/${l}/`,display:"standalone",background_color:"#f8fafc",theme_color:"#2563eb",icons:[{src:"/icons/edgeone-icon.svg",sizes:"any",type:"image/svg+xml",purpose:"any maskable"}]};fs.writeFileSync(path.join(dir,"manifest.webmanifest"),`${JSON.stringify(m,null,2)}\n`);const off=`<!doctype html><html lang="${l}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><title>${esc(o.offline)} | EdgeOne Page</title><style>:root{color-scheme:light dark;font-family:system-ui,sans-serif}body{min-height:100vh;margin:0;display:grid;place-items:center;background:#f8fafc;color:#0f172a}main{max-width:640px;padding:48px;text-align:center}h1{font-size:5rem;color:#2563eb}p{color:#64748b;line-height:1.8}a,button{display:inline-block;margin:.5rem;padding:.8rem 1.2rem;border:0;border-radius:.75rem;background:#2563eb;color:#fff;text-decoration:none;font:inherit}@media(prefers-color-scheme:dark){body{background:#020617;color:#e2e8f0}}</style></head><body><main><h1 aria-hidden="true">↯</h1><h2>${esc(o.offline)}</h2><p>${esc(o.message)}</p><a href="/${l}/">${esc(o.home)}</a><button id="reload">${esc(o.reload)}</button></main><script>document.getElementById("reload").onclick=()=>location.reload()</script></body></html>`;fs.writeFileSync(path.join(dir,"offline.html"),off);finalize(root)}
hexo.extend.filter.register("after_render:html",inject);hexo.extend.filter.register("after_generate",generate);module.exports={finalizeServiceWorker:finalize,injectMetadata:inject,serviceWorkerSource:worker,structuredData:schema,writePwaFiles:generate};
